### ISSUE TITLE
What should /sign_in dialog do if /wsapi/list_emails returns an empty list

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1472]
We talked about this in the triage meeting, and noted that GH-759 is the covering issue that needs to be addressed. However, I'm filing this as a separate issue about how the dialog should behave if it ever gets back an empty email list (for whatever reason).

Steps to reproduce this empty list:
1. Initial condition: two browsers that have both already authenticated for the same email address. This account has only that one single email address associated with it.
2. With browser-1, click signin for beta.myfavoritebeer.org. In the /sign_in dialog, click 'this is not me'.
3. Enter the same email as before, then click 'forgot your password' and then 'reset password'. Load the link in the email, enter a "new" password, etc., and browser-1 is now re-authed for that email address, and is logged in to beta.myfavoritebeer.org.
4. With browser-2, click signin. 

Expected: 

Either I should have a choice to signin with the email I'd used previously with this browser, or I should be given the textbox to enter an email address and then password.

Actual:

I get a dialog box with no email list and a 'sign in' button. Clicking 'sign in' puts up an alert with 'The selected email is invalid or has been deleted'.

![img](https://img.skitch.com/20120419-bhh4p2u15ucwgdg8qgcuya27ae.png)

When the dialog comes up, the call to /wsapi/session_context returns 200 OK, with payload '"authenticated":true,"auth_level":"password"'.
The call to /wsapi/list_emails is also 200 OK, and returns payload '{}'. 

Workaround:

In browser-2, click 'this is not me', and then enter the email address and (now-not-forgotten) password.

**Comment by jrgm** [comment]
See also Lloyd's comments for other ways to cause this to happen - https://github.com/mozilla/browserid/issues/2090#issuecomment-7074219

**Comment by jrgm** [comment]
Marking for beta2. It would be better to prompt if list_emails is empty, than to show this non-working UI.

**Comment by jrgm** [comment]
See also https://github.com/mozilla/browserid/issues/2246#issuecomment-7812810 for STR.

**Comment by jrgm** [comment]
@seanmonstar - can you have a look at bailing gracefully out of this state (for whatever reason it can happen).

**Comment by seanmonstar** [comment]
As I tried to reproduce this using the STR, I ran into the new flow that is on dev: By forgetting my password in one browser, my session was invalidated in the other. I was forced to login again, typing the email and password. I didn't get a list of no emails.

Could this be fixed because of the session invalidation, or are there other instances this happens?

**Comment by zaach** [comment]
@seanmonstar yep, the original case here should be resolved because of session invalidation on password updates, but the general problem (empty email lists) still remains.

If an email address that exists on account A is added to a account B, we could invalidate the session of account A, but only if that was its only email address. That would seem to solve the empty list problem. Should we also invalidate account A's session when it has extra emails?

**Comment by jaredhirsch** [comment]
Out of dev time in Beta 2; bumping to Beta 3.

**Comment by jaredhirsch** [comment]
@jrgm I'm unable to repro the empty list using original STR. Closing--please reopen with new STR if this bug is still a bug.

**Comment by jrgm** [comment]
@zaach's scenario (also lloyd's in #2090) is still reproducible. Reopening.

**Comment by jrgm** [comment]
I originally put in this issue as a followup. Even if a core bug is fixed, this was about 'how the dialog should behave if it ever gets back an empty email list (for whatever reason).'

**Comment by jrgm** [comment]
In other words, can the frontend just bail if list_emails === {}.

**Comment by jaredhirsch** [comment]
@shane-tomlinson seems like there should be a spot in the state machine where we could check if list_emails is empty, and bail back to the enter your email screen. thoughts?

**Comment by shane-tomlinson** [comment]
@6a68, @jrgm - do we know why list_emails is returning an empty set of emails?

**Comment by seanmonstar** [comment]
I just hit this: I logged in with a brand new email. Afterwards, in another
browser, I logged into my normal account, and used "Add another email", and
added the same email I used previously that was brand new. It "stole" the
email from the brand new account. Trying to use it, I was still logged in,
but the list was empty.

**Comment by jrgm** [comment]
No, really, we need to fix this. @seanmonstar's case is reproducible, as are others (https://github.com/mozilla/browserid/issues/1472#issuecomment-20322113).

I've kept this open as the "null-check" case: https://github.com/mozilla/browserid/issues/1472#issuecomment-20395992 , i.e., if list_emails returns '{}' then we should just bail.

I'm going to bump this to 5-star, so it gets noticed a little more, and then we can figure out real priority on trains.

**Comment by seanmonstar** [comment]
So, should I add an error screen here? Or force a logout?

**Comment by jrgm** [comment]
I was thinking that forcing the logout and prompting for an email address would be the right response. (This is just taking the only action that a resonable user would take (i.e., "This is not me")).

**Comment by shane-tomlinson** [comment]
@jrgm - I am unable to reproduce using the STRs in the description, what I do see however is that Browser 2 is still able to create an assertion for the email address even after Browser 1 has reset the password.

STR
1. In 2 browsers, open the dialog to the email picker using the same email address.
2. In browser 1, click "this is not me"
3. In browser 1, enter email address from step 1, click "forgot password?"
4. In browser 1, open password reset link.
5. In browser 2, click "sign in."
6. Shouldn't browser 2 sync email addresses and sign you out?
