### ISSUE TITLE
User has to type password 4 times when confirming on browser other than initiator

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1555]
A new user has to type their password 4 times when confirming their email on a browser other than the initiating browser.  This could happen if a user signs up for BrowserID on a mobile device and confirms on a desktop device.

Passwords 1 and 2 are needed in the dialog before the verification email is sent.
Password 3 is required in browser 2 when verifying email
Password 4 is required in the dialog after verifying email but before assertion is generated.

@lloyd - you believed you had a backend fix for this?

**Comment by shane-tomlinson** [comment]
@lloyd - checkin e54da630b4b5b8164137471ad5895011300e41a1 is the initial checking for this.  

This checkin does not handle the case where an account goes from being an account with only primary addresses to an account with its first secondary email and the email was validated in another browser.

STR:

1) Open 2 browsers.
2) In Browser 1, create an account with a primary address
3) In Browser 1, add the first secondary address to account, set password, go to "check your email page"
4) In Browser 2, open verification link
5) In Browser 1, user has to type password.

**Comment by lloyd** [comment]
The pull request has been merged.  this issue is fixed.

**Comment by jrgm** [comment]
Bah, sorry for not getting to this earlier in the week. The 2-browser new secondary and add-secondary-to-secondary work (only 3 passwords required, not a 4th in the dialog again). 

However, I still get a 4th challenge in the browser1 when adding a secondary to a primary-only account (per STR in https://github.com/mozilla/browserid/issues/1555#issuecomment-5873009). Reopening.

**Comment by shane-tomlinson** [comment]
Link to #1451

**Comment by shane-tomlinson** [comment]
Closing as dup of #1682.
