### ISSUE TITLE
Password field not cleared on /signin page if user changes email address

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2297]
STR

1) Open /signin page
2) Enter in an incorrect email address that will create a new secondary account
3) Start typing a password
4) Change the email address to a known secondary account
5) Hit Enter
6) Password field is not cleared.

**Comment by quack1** [comment]
I can't reproduce this bug. When I type (in step 2) an unknown email address, I type a password to create the second account, and (step 4) I press 'cancel' to go back and enter a known email address. I hit Enter, and the password field is clear.

The issue is old (9 month) so I think we can close it, it has been solved by past updates.

**Comment by callahad** [comment]
Yep, seems like this has been fixed. Thanks, @quack1!

**Comment by quack1** [comment]
You're welcome! Seems that I didn't even have to write code to help on my first bug! \o/

**Comment by callahad** [comment]
@quack1 Checking to see if bugs are still valid is _really_ helpful. Thank you. :)

**Comment by quack1** [comment]
Yes, I'm searching for simple bugs for me to start helping, and I'm also cheeking if they are still real issues!
