### ISSUE TITLE
Fails to login in IE10 with Windows 8 (via gmail)

### ISSUE THREAD

**Issue by ggaughan** [mozilla/persona#3998]
Signing in with IE10 on Windows 7 and Windows 8 (VMs from msmodern.ie) using a gmail account fails.

Initially (and with cleared cache) prompts for email as usual and then shows google form prompting for email address again and password. Then shows:

```
Error
Something went wrong. Please try again later.
[Cancel]
Error: Invalid or missing claim.
```

(Works ok on Windows 7 with Firefox on same site with same email; and fine with Chrome/Firefox on Ubuntu)

**Comment by shane-tomlinson** [comment]
Hi @ggaughan - I just tried on Win7/IE10 without a problem. Is our windows 32 or 64 bit? What are your security settings? The screen that you see, is it branded as Mozilla Persona or Google?

**Comment by shane-tomlinson** [comment]
@ggaughan - If you are comfortable telling us which site you can sign in to, perhaps we can see if there are any obvious problems.

**Comment by ggaughan** [comment]
Hi Shane,

I retried in Win 7 and it did work eventually. Win 8 still fails however.

The screen asking for a password and the email again is Google branded.

Windows 32-bit, IE 10.0.9200.16384. Default security settings from the Microsoft VM/IE.

(I'll email you the site link.)

**Comment by csuciu** [comment]
I'm able to reproduce in stage/prod using Win 8 x86 & IE10.
After entering the gmail credentials in the google branded dialog, I get the "Something went wrong....." error message. After that, trying to sign again with same/other gmail address will trigger the error message right after entering the email and pressing on sign in.

Can't reproduce on: 
- Win 7 x64 & IE10 
- Win 8 x64 & IE10

**Comment by callahad** [comment]
Tagging as 5-star to see if we can also reproduce...

**Comment by pdehaan** [comment]
Unable to repro on 123done.org w/ Windows 8.1 Pro Preview (from modern.ie/Parallels 9), 32-bit OS; x64-based processor, and IE 11.0.9431.217 (using my Gmail acct)

Unable to repro on 123done.org w/ Windows 8 Enterprise Eval (from modern.ie/Parallels 9), 32-bit OS; x64-based processor, and IE 10.0.9200.16519 (using my Gmail acct)

@ggaughan @csuciu -- are you guys still able to repro this? I think we pushed a change recently for IE11, but I'm not sure when that went live on production servers.

**Comment by csuciu** [comment]
@pdehaan I'm still able to reproduce this on 123done/beta.123done 
Windows 8 Enterprise, 32-bit OS, x64-based processor and IE 10.0.9200.16688

I tried on a clean profile.

**Comment by ggaughan** [comment]
Still fails for me too: 

  Windows 8, 32-bit
  IE 10.0.9200.16721  (update versions 10.0.10 (KB2879017))

**Comment by shane-tomlinson** [comment]
This may be 32 bit specific. Everything WFM on 64 bit Windows 8/Windows 8.1

**Comment by csuciu** [comment]
I'm able to reproduce this issue on Win 8.1 Pro x32/x64 and IE 11.0.9600.16438

**Comment by darkwing** [comment]
I've noticed this periodically on MDN as well.  With a Gmail account, I sometimes see this:

http://screencast.com/t/rqqpFw7M

Other times I see the error listed in the initial bug report:

http://screencast.com/t/FMi1DXDLEn

I'm having success logging in with a non-GMail account.  Could this be a sign of race condition, seeing an error on the persona side sometimes, and seeing an error on Google the others?

Since is the presently happening on MDN, (https://bugzilla.mozilla.org/show_bug.cgi?id=975835), can we escalate this.

**Comment by darkwing** [comment]
Admittedly we are on an older version of Persona, so please let me know if this was reported before.

**Comment by darkwing** [comment]
Additionally, if I clear my cache, I'm able to log in with any email address without issue.

**Comment by jaredhirsch** [comment]
Based on the notes in this bug, it seems like we have repro'd, but only on 32-bit Win 8, IE10.

Bumping down to four stars, since we've determined the extent of the impact.

**Comment by julienfastre** [comment]
Hi,

We could reproduce the bug with win 8 & IE11.

This is what we get with an attempt to connect with some *@gmail.com address : 

![screen shot 2014-05-08 at 17 43 08](https://cloud.githubusercontent.com/assets/345600/2929396/1cd47774-d789-11e3-9d28-e151add4dfe4.png)

**Comment by jaredhirsch** [comment]
Hi @julienfastre - thanks for adding this. Do you know if you were on win8 x32 or x64?

**Comment by julienfastre** [comment]
@6a68 : we were on win8 x64.

Thanks.

**Comment by darronz** [comment]
Can reproduce this using Safari 8.0 (10600.1.22) on OS X Yosemite Beta 10.10 (14A361c). Not sure if it is helpful but my Google account uses 2 Factor auth.

**Comment by jaredhirsch** [comment]
@julienfastre @darronz If you could visit https://people.mozilla.org/~fmarier/troubleshoot.html and screenshot or copy/paste the output, that would help with troubleshooting--although I don't know who actually has time to fix it (if it's a legit bug). My guess is that you both have third-party cookies blocked, not sure though.

**Comment by darronz** [comment]
Thanks @6a68 - you're quite right. I had mine set to "Allow from current website only"; switching to "Allow from websites I visit" allowed me to log in.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by jimvanderveen** [comment]
I had this same issue this morning (2015-12-01). Third-party cookie setting fixed it. (I had the same settings as darronz.) 

The 3rd-party cookie requirement might be something you should highlight.
